# Dev container. This is larger than the runtime container 
FROM python:3

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY keyhole.py ./

CMD ["python", "./keyhole.py"]

